// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjXlTD5v8ClsjcgvUCGwW9Nj7oZJLFfYw',
    appId: '1:57924925690:web:cb0c96601f14f2b1347143',
    messagingSenderId: '57924925690',
    projectId: 'app-distribution-6a785',
    authDomain: 'app-distribution-6a785.firebaseapp.com',
    storageBucket: 'app-distribution-6a785.appspot.com',
    measurementId: 'G-2YQW8TZNP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJrXpl6gW86qsffxENY8PWhmNSdtSphQI',
    appId: '1:57924925690:android:71ca47918824a9ed347143',
    messagingSenderId: '57924925690',
    projectId: 'app-distribution-6a785',
    storageBucket: 'app-distribution-6a785.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYP55nU-qrYBegHtROxdwG8CtBhi6tKYY',
    appId: '1:57924925690:ios:150cea4c93ca6118347143',
    messagingSenderId: '57924925690',
    projectId: 'app-distribution-6a785',
    storageBucket: 'app-distribution-6a785.appspot.com',
    iosBundleId: 'com.example.ciCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYP55nU-qrYBegHtROxdwG8CtBhi6tKYY',
    appId: '1:57924925690:ios:150cea4c93ca6118347143',
    messagingSenderId: '57924925690',
    projectId: 'app-distribution-6a785',
    storageBucket: 'app-distribution-6a785.appspot.com',
    iosBundleId: 'com.example.ciCd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjXlTD5v8ClsjcgvUCGwW9Nj7oZJLFfYw',
    appId: '1:57924925690:web:c9c36096a2879945347143',
    messagingSenderId: '57924925690',
    projectId: 'app-distribution-6a785',
    authDomain: 'app-distribution-6a785.firebaseapp.com',
    storageBucket: 'app-distribution-6a785.appspot.com',
    measurementId: 'G-60SED8LKT0',
  );
}
