# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --no-tree-shake-icons"
    release = firebase_app_distribution(
                app: "1:57924925690:android:71ca47918824a9ed347143",
                firebase_cli_token: "1//03UZnStkXyN7pCgYIARAAGAMSNwF-L9IrVVlUzR7UA2kN_q4Ja-wrYRKM4_ffhgxz4eTClubktTVMvmIzFcZf0kK_1tpEICcsdys",
                android_artifact_type: "APK",
                android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
            )
  end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
end
