name: Testing Flow

on:
  push:
    branches :
      - master

  pull_request :
    branches :
      - master

jobs:
  build:
    # Install the OS
    name: Install OS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the target repository
      - name: Check out the target repository
        uses: actions/checkout@v4
        with:
          repository: bolespolo4/qara_perswonal_testing
          path: packages

      # Step 2: Print the current working directory
      - name: Print current working directory
        id: pythonDir
        run: |
          pwd; ls; 
          echo "\n"
          echo "^^^^ \n ^^^^" 
          cd packages/lib/core/python
          echo "pythonFilePath=$(pwd)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Choose the Python version you need

      # Step 4: Install the pyYAML package
      - name: Install PyYAML
        run: python -m pip install PyYAML  # Install PyYAML using pip

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      # Step 6: Get Secrets
      - name: Get Secrets
        id: getSecrets
        run: |
          echo -n '${{ secrets.APP_CONFIG }}' | base64 --decode > file.env
          cat file.env
          echo "envFile=$(pwd)/file.env" >> $GITHUB_OUTPUT
          
      # Step 7: Run Python Script
      - name: Execute python script
        run: | 
          python "${{ steps.pythonDir.outputs.pythonFilePath }}/yaml_gen.py" ${{ steps.getSecrets.outputs.envFile }}

      # Step 8: Move YAML File
      - name: Move YAML File to main project
        run: |
          pwd; ls
          mv flavorizr.yaml ../
          pwd; ls
