name: Testing Flow

on:
  push:
    branches :
      - master

  pull_request :
    branches :
      - master

jobs:
  build:
    name: Run Python script
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the target repository
      - name: Check out the target repository
        uses: actions/checkout@v4
        with:
#          fetch-depth:
#          repository: https://github.com/bolespolo4/qara_perswonal_testing.git
          repository: bolespolo4/qara_perswonal_testing
          path: packages
          # Optional: specify the ref (branch/tag) to check out

      # Step 2: Print the current working directory
      - name: Print current working directory
        id: pythonDir
        run: |
          pwd; ls; 
          echo "\n"
          echo "^^^^ \n ^^^^" 
          cd packages/lib/core/python
          echo "pythonFilePath=$(pwd)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

#      # Step 4: Set up Python
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.9  # Choose the Python version you need
#
      # Step 5: Install the pyYAML package
      - name: Install PyYAML
        run: python -m pip install PyYAML  # Install PyYAML using pip

      # Step 6: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Get Secrets
        id: getSecrets
        run: |
          echo -n ${{secrets.APP_CONFIG}} | base64 --decode > file.env
          cat file.env

      - name: execute python script
        run: |
          echo "${{ steps.pythonDir.outputs.pythonFilePath }}"
          python "${{ steps.pythonDir.outputs.pythonFilePath }}/yaml_gen.py"
          
