name: Testing Flow

on:
  push:
    branches :
      - master

  pull_request :
    branches :
      - master

jobs:
  build:
    name: Run Python script
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository containing the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Check out the target repository
      - name: Check out the target repository
        uses: actions/checkout@v4.1.6
        with:
          repository: bolespolo4/qara_perswonal_testing
          path: lib
          # Optional: specify the ref (branch/tag) to check out
          ref: master

      # Step 3: Print the current working directory
      - name: Print current working directory
        run: pwd

      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Choose the Python version you need

      # Step 5: Install the pyYAML package
      - name: Install PyYAML
        run: python -m pip install PyYAML  # Install PyYAML using pip

      # Step 6: Install dependencies
      - name: Install dependencies
        run: |
          cd lib/core/python
          python -m pip install --upgrade pip

     
