name: Testing Flow

on:
  push:
    branches :
      - master

  pull_request :
    branches :
      - master

jobs:
  build:
    name: Run Python script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Choose the Python version you need

      - name: Install PyYAML
        run: python -m pip install PyYAML  # Install PyYAML using pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script
        run: python env_to_yaml.py